# Usa una imagen base oficial de Python
FROM python:3.11-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de requerimientos 
COPY requirements.txt requirements.txt

# Instala las dependencias
RUN pip install -r requirements.txt

# Copia el resto de los archivos de la aplicacion
COPY . .

# Expone el puerto en el que la aplicacion correra
EXPOSE 5000

# Define el comando por defecto para correr la aplicacion
CMD [ "python", "app.py" ]